server:
  port: 8050

aws:
  queue:
    payment-request: solicitar-pagamento
  topic:
    status-payment: status-pagamento

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
  sql:
    init:
      platform: postgres